### ISSUE TITLE
Provide MSYS2 packages for Windows

### ISSUE THREAD

**Issue by kou** [red-data-tools/want-to-do#1]
If we create `pacman` packages for Apache Arrow and related products and submit them to https://github.com/alexpux/msys2-packages, users will be able to install Apache Arrow by `pacman -Ss apache-arrow`.

**Comment by dsisnero** [comment]
+1 .  That would be great.

**Comment by kou** [comment]
Do you want to work on this?

**Comment by kou** [comment]
Done.
