### ISSUE TITLE
OpenAI Gym for Ruby

### ISSUE THREAD

**Issue by kou** [red-data-tools/want-to-do#15]
https://github.com/openai/gym

https://github.com/kojix2/openai_gym is a Ruby wrapper for OpenAI Gym. Should we improve this? Or should we re-implement the original OpenAI Gym in Ruby?

**Comment by kojix2** [comment]
Hahaha
`openai_gym` is a joke gem. We should not improve this gem. I removed openai_gym from the RubyGem server. 

I created `openai_gym` for this.
http://medfreak.info/?p=3293

**Comment by kojix2** [comment]
I don't have enough time to update my knowledge about neural networks these days.
They are pretty difficult for me.

But, If I have to play with OpenAI Gym again, I will use this.
https://github.com/openai/gym-http-api
(However, some people say gym-http-api is not good in performance. )
Maybe we can close this issue.

**Comment by kou** [comment]
There is the Ruby bindings: https://github.com/openai/gym-http-api/tree/master/binding-Ruby
