### ISSUE TITLE
Create binding of XGBoost

### ISSUE THREAD

**Issue by kou** [red-data-tools/want-to-do#8]
https://github.com/dmlc/xgboost

**Comment by youchan** [comment]
https://github.com/dmlc/xgboost/issues/2427#issuecomment-340044287

**Comment by youchan** [comment]
They have already done. https://github.com/PairOnAir/xgboost-ruby

**Comment by kou** [comment]
We should join to the project instead of creating a new project.

**Comment by kojix2** [comment]
Ankane work
https://github.com/ankane/xgboost
